name: CI

on:
    workflow_dispatch:

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_artifacts:
        permissions:
            contents: read
        uses: ./.github/workflows/app-build-common.yml
        with:
            artifact_prefix: ci
            publish_release: false
        secrets: inherit
